
# not currently implemented
# patchsize: 0

features:
  - name: my features
    type: ordinal
    files:
      - directory: /home/lb/data/GA-cover
    transforms:
      - centre
      - standardise
    imputation: none
  
  - name: my features
    type: categorical
    files:
      - directory: /home/lb/data/GA-cover/cat_datasets
    transforms:
    imputation: nn

# mask file used for masking prediction grid
# Mask with values=retain will be predicted
mask:
  file: /home/lb/data/GA-cover/mask/old_mask_test.tif
  retain: 1

targets:
  file: /home/sudipta/GA_data/GA-cover2/geochem_sites.shp
  property: Na_ppm_i_1

learning:
    algorithm: cubist
    arguments:
      max_rules: 500
      committee_members: 20
      unbiased: False
      max_categories: 5000
      target_transform: standardise
      neighbors: 5
      sampling: 50
      seed: 2

#    algorithm: multicubist
#    arguments:
#      outdir: .
#      trees: 10
#      max_rules: 500
#      committee_members: 20
#      unbiased: False
#      max_categories: 5000
#      target_transform: standardise
#      neighbors: 5
#      sampling: 50
#      seed: 2
#      parallel: True

prediction:
  quantiles: 0.95

validation:
  # - feature_rank
  - parallel
  - k-fold:
      folds: 5
      random_seed: 1
  
output:
  directory: .

