
# not currently implemented
# patchsize: 0

features:
  - name: my features
    type: ordinal
    files:
      - directory: /home/lb/data/GA-cover
    transforms:
      - centre
      - standardise
    imputation: none
  
  - name: my features
    type: categorical
    files:
      - directory: /home/lb/data/GA-cover/cat_datasets
    transforms:
    imputation: nn

# mask file used for masking prediction grid
# Mask with values=retain will be predicted
mask:
  file: /home/lb/data/GA-cover/mask/old_mask_test.tif
  retain: 1

targets:
  file: /home/sudipta/GA_data/GA-cover2/geochem_sites.shp
  property: Na_ppm_i_1

learning:
    algorithm: cubist
    arguments:
      max_rules: 500
      committee_members: 20
      unbiased: False
      max_categories: 5000
      target_transform: standardise
      neighbors: 5
      sampling: 50
      seed: 2

# neighbors: int, number of nearest neighbors to be used (1-9)
# nearest-neighbor model: predicts the target value of a new case by finding
# the n most similar cases in the training data,
# and averaging their target values.

# max_categories: number of max categories in categorical data

# max_rules: use this to control overfitting (int: 1-1000000)

# committee_members: number of committees to use (int: 1-100)

# outdir: directory where intermediate model files are stored

# trees: number of cubist jobs, trees X committee_memebers will be the total
# number of trees

# extrapolation: allowed max deviation of predictions from
# training targets float between 0-100.

# sampling: random sampling expressed in % terms to be  used during training

# parallel: train cuist jobs in parallel

# unbiased: whether to train unbiased trees. Use unbiased=True for more skewed
# target distribution

# composite_model: Use rule based model or composite model?
# composite_model=True improves on rule based models, but in addition
# does the equivalent of krigging.

# target_transform: target transform (choice: stardardise, sqrt, log, identity',
# logistic, rank, kde)

#    algorithm: multicubist
#    arguments:
#      outdir: .
#      trees: 10
#      max_rules: 500
#      committee_members: 20
#      unbiased: False
#      max_categories: 5000
#      extrapolation: 5
#      target_transform: standardise
#      neighbors: 5
#      sampling: 50
#      seed: 2
#      composite_model: True
#      parallel: True

prediction:
  quantiles: 0.95

validation:
  # - feature_rank
  - parallel
  - k-fold:
      folds: 5
      random_seed: 1
  
output:
  directory: .

