
# not currently implemented
# patchsize: 0

features:
  - name: my features
    type: ordinal
    files:
      - directory: /home/lb/data/GA-cover
    transforms:
      - centre
      - standardise
    imputation: nn
  
  - name: my features
    type: categorical
    files:
      - directory: /home/lb/data/GA-cover/cat_datasets
    transforms:
    imputation: nn 


targets:
  file: /home/lb/data/GA-cover/geochem_sites.shp
  property: Na_ppm_i_1

learning:
    algorithm: cubist
    arguments:
      max_rules: 500
      committee_members: 20
      unbiased: False
      max_categories: 5000
      target_transform: rank

prediction:
  quantiles: 0.95

validation:
  # - feature_rank
  # - k-fold:
  #     folds: 5
  #     random_seed: 1
  
output:
  directory: .

