
# not currently implemented
# patchsize: 0

features:
  - name: my features 1
    type: ordinal
    files:
      # - path: /home/lb/data/GA-cover/Th_v1.tif
      # - list: /home/lb/data/GA_Cover2_sirsam_LLC/sirsam_covariates_convolved.txt
      - directory: /home/lb/data/GA-cover
    # transforms are performed in order
    transforms:
      - centre
      - standardise
    imputation: none
  
  - name: my features 2
    type: categorical
    files:
      # - path: /home/lb/data/GA-cover/Th_v1.tif
      # - list: /path/to/csv_file.csv
      - directory: /home/lb/data/GA-cover/cat_datasets
    # transforms are performed in order
    transforms:
      - randomhot:
          n_features: 10
          seed: 1
    imputation: none

# mask file used for masking prediction grid
# Mask with values=retain will be predicted
mask:
  file: /home/lb/data/GA-cover/mask/old_mask_test.tif
  retain: 1

preprocessing:
  # imputation: none
  # imputation: gaus
  # imputation: nn
  imputation: mean

  transforms:
    # - whiten:
        # keep_fraction: 0.8

targets:
  file: /home/lb/data/GA-cover/geochem_sites.shp
  property: K_ppm_imp_

clustering:
  file: /home/lb/data/GA-cover/geochem_sites_class1.shp
  property: class
  algorithm: kmeans
  arguments:
    n_classes: 12
    oversample_factor: 5

learning:
    # algorithm: sgdapproxgp
    # arguments:
    #     target_transform: standardise
    #     kern: rbf
    #     lenscale: 1000
    #     ard: True
    #     maxiter: 5000
    #     nbases: 50
    #     random_state: 1
    algorithm: randomforest
    arguments:
      n_estimators: 500
      target_transform: standardise

prediction:
  quantiles: 0.95

validation:
  #- feature_rank
  - parallel
  - k-fold:
      folds: 5
      random_seed: 1
  
output:
  directory: .

